import { z } from "zod";

/**
 * The only content types the platform stores. Enforced twice: at upload-url
 * time (this schema) and again at attach time against what storage actually
 * reports for the uploaded object — the client is never the authority.
 */
export const IMAGE_CONTENT_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/avif",
] as const;

/** Server-side ceiling per image. The client downscales well below this. */
export const MAX_IMAGE_BYTES = 10 * 1024 * 1024;

export const MEDIA_SCOPES = ["property", "room"] as const;
export type MediaScope = (typeof MEDIA_SCOPES)[number];

// Keys are generated by the backend (`<scope>/<ts>-<safe-filename>`); this
// pattern re-validates them on attach so a forged key can't traverse scopes
// or reference arbitrary bucket paths.
export const mediaKeyPattern = /^(property|room)\/[a-zA-Z0-9][a-zA-Z0-9._-]*$/;

export const requestUploadSchema = z.object({
  scope: z.enum(MEDIA_SCOPES),
  filename: z.string().min(1).max(200),
  contentType: z.enum(IMAGE_CONTENT_TYPES),
});
export type RequestUploadInput = z.infer<typeof requestUploadSchema>;

export const attachMediaSchema = z.object({
  /** Storage key returned by the upload-url step. The server derives the URL. */
  key: z.string().min(1).max(300).regex(mediaKeyPattern, "Invalid media key"),
  altText: z.string().trim().max(200).optional(),
});
export type AttachMediaInput = z.infer<typeof attachMediaSchema>;

export const updateMediaSchema = z.object({
  altText: z.string().trim().max(200).nullable(),
});
export type UpdateMediaInput = z.infer<typeof updateMediaSchema>;

export const reorderMediaSchema = z.object({
  /** Complete new order — every media id of the gallery, first = cover. */
  mediaIds: z.array(z.string().min(1).max(64)).min(1).max(100),
});
export type ReorderMediaInput = z.infer<typeof reorderMediaSchema>;
